#Set the parameters of the robot system
wheel_radius: 0.062
robot_wheelbase: 0.330

#Set parameters of the simulation node
sim_sample_time: 0.02
sim_node_rate: 100

#Set parameters of the localisation node
localisation_sample_time: 0.02
localisation_node_rate: 100
localisation_noise: True

#Set parameters of the Joint Publisher node
joint_sample_time: 0.02
joint_node_rate: 100

#Set parameters of the Open Loop Ctrl node
ctrl_linearSpeed: 0.3
ctrl_angularSpeed: 0.3
ctrl_corners: 6
ctrl_edgeLenght: 3.0
controller_node_rate: 100

#Set the parameters of the Closed Loop Controller
control_kp_d: 0.09
control_ki_d: 0.00
control_kp_th: 0.3
control_ki_th: 0.000
controller_sample_time: 0.02
goal_radius: 0.2
control_node_rate: 100

#target_link: "sim1/base_link"
#source_link: "world"

sim1:
  #Set initial conditions of the robot 1
  pos_x0: 1.00
  pos_y0: 1.00
  pos_th0: 0.0

sim2:
  #Set initial conditions of the robot 2
  pos_x0: 0.00
  pos_y0: 0.00
  pos_th0: 0.00